apiVersion: apps/v1
kind: Deployment
metadata:
  name: des2-app-route
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: des2-app-route
  template:
    metadata:
      name: des2-app-route
      labels:
        app.kubernetes.io/name: des2-app-route
    spec:
      containers:
        - name: des2-app-route
          image: artusc/des2-app-route
          ports:
            - containerPort: 3000